### ISSUE TITLE
重复设置setPercent无法更改进度条

### ISSUE THREAD

**Issue by crazyzjw** [xintanggithub/TextSeekBar#3]
就只有第一次设置有效果
`<com.tson.text.seekbar.MultiSeekBar
    android:id="@+id/multiSeekBarMSB"
    android:layout_width="match_parent"
    android:gravity="center_vertical"
    android:layout_height="wrap_content">
    
    <LinearLayout
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:background="@drawable/bg_radius18_bg"
        android:backgroundTint="#336699"
        android:paddingHorizontal="5dp"
        android:gravity="center_vertical"
        android:orientation="horizontal">

        <TextView
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:text="123" />

        <ImageView
            android:layout_width="24dp"
            android:layout_height="24dp"
            android:src="@drawable/_image_camera" />
    </LinearLayout>

    
    <com.tson.text.seekbar.TextSeekBar
        android:layout_width="match_parent"
        android:layout_height="20dp"
        android:layout_centerInParent="true"
        app:backgroundProgressBarColor="#FAB282"
        app:backgroundProgressBarEndColor="#FB6501"
        app:backgroundProgressBarHeight="8dp"
        app:backgroundProgressBarStartColor="#FFE8D9"
        app:progress="0"
        app:prospectProgressBarColor="#B18BF4"
        app:prospectProgressBarEndColor="#630DFB"
        app:prospectProgressBarHeight="8dp"
        app:prospectProgressBarStartColor="#F6F1FF"
        app:thumbHide="true" />
</com.tson.text.seekbar.MultiSeekBar>`

**Comment by xintanggithub** [comment]
Resolved in version 1.0.6

**Comment by crazyzjw** [comment]
> Resolved in version 1.0.6

好像..你那边没更新到

**Comment by xintanggithub** [comment]
应该是更新过的，示例代码 `MainActivity` 中有通过递归更新进度的测试验证代码。

```kotlin
class MainActivity : AppCompatActivity() {

    private var percent = 0.0f

    ...
    ...

    /**
     * 递归更新multiSeekBar进度
     */
    private fun looperAdd() {
        if (percent in 0f..1f) {
            percent += 0.005f
            runOnUiThread {
                // 支持shape的
                shapeBgMB.percent(percent)
                // 自定义thumb的
                multiSeekBarMSB.percent(percent)
            }
            Handler().postDelayed({
                looperAdd()
            }, 15)
        }
    }

}
```
