### ISSUE TITLE
初始化控件时候就设置percent会出现没进度颜色,thumb是正确移动的情况

### ISSUE THREAD

**Issue by crazyzjw** [xintanggithub/TextSeekBar#4]
`<com.tson.text.seekbar.MultiSeekBar
            android:id="@+id/shapeBgMB"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:gravity="center_vertical"
            app:backgroundProgress="@drawable/bg_radius18_bg"
            app:backgroundProgressHeight="10dp"
            app:prospectProgress="@drawable/bg_radius18_pb"
            app:prospectProgressHeight="11dp">
    
            
            <LinearLayout
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:background="@drawable/bg_radius18_bg"
                android:backgroundTint="#336699"
                android:gravity="center_vertical"
                android:orientation="horizontal"
                android:paddingHorizontal="5dp">

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:text="123" />

                <ImageView
                    android:layout_width="24dp"
                    android:layout_height="24dp"
                    android:src="@drawable/_image_camera" />
            </LinearLayout>

        </com.tson.text.seekbar.MultiSeekBar>`

**Comment by crazyzjw** [comment]
`        postDelayed({ csb_read_plan_course_list_header.percent(percent) }, 50)
`
加了个延时就正常了,看到是源码是测量时候延时了,但是初始化时候延时会影响绘制

**Comment by xintanggithub** [comment]
已更新：v1.0.7
notice：Update view by post
