### ISSUE TITLE
还有点小问题哈

### ISSUE THREAD

**Issue by crazyzjw** [xintanggithub/TextSeekBar#5]
`<com.tson.text.seekbar.MultiSeekBar
            android:id="@+id/shapeBgMB"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:gravity="center_vertical"
            app:backgroundProgress="@drawable/bg_radius18_bg"
            app:backgroundProgressHeight="10dp"
            app:prospectProgress="@drawable/bg_radius18_pb"
            app:prospectProgressHeight="11dp">
    
            
            <LinearLayout
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:background="@drawable/bg_radius18_bg"
                android:backgroundTint="#336699"
                android:gravity="center_vertical"
                android:orientation="horizontal"
                android:paddingHorizontal="5dp">

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:text="123" />

                <ImageView
                    android:layout_width="24dp"
                    android:layout_height="24dp"
                    android:src="@drawable/_image_camera" />
            </LinearLayout>

        </com.tson.text.seekbar.MultiSeekBar>`

发现两个问题:
1.滑动不流畅,手指拖动会一卡一卡
2.当进度条在10%之前时候会出现,进度颜色的圆弧露出了..后面进度是正常...

**Comment by xintanggithub** [comment]
1.0.8： 进度条偏移量bugfix
关于滑动不流畅，可以提供一下设备信息（配置和品牌）吗？

**Comment by crazyzjw** [comment]
> 

一加手机的,android10 ,配置不错的

**Comment by crazyzjw** [comment]
还有个问题就是可以设置thumb的偏移量?,因为经常出现ui切图的是有内边距透明,如果设置背景色是有边框就0%进度时候,看到边框..盖不全

**Comment by crazyzjw** [comment]
现在0%进度也是会有一点进度色了..

**Comment by xintanggithub** [comment]
1.0.9已添加offset属性 **multiThumbOffset** ，可以避免露底，参考readme。
关于卡顿的问题，在老机型小米3（对比现在的手机应该是配置很低的）上验证未出现问题，但是现在添加了刷新间隔interval参数，可以通过它设置刷新间隔。如果仍然卡顿，可查看是否在回调中有耗时处理，或者可以fork源码对dispatchTouchEvent做自定义偏好限制
